<?php

namespace Dataview\IOCompany;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AttributeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('attributes')->insert([
            ['character_set_id' => 1, 'id' => 1, 'title' => 'Visionário', 'slug' => 'visionario'],
            ['character_set_id' => 2, 'id' => 2, 'title' => 'Persuasivo', 'slug' => 'persuasivo'],
            ['character_set_id' => 3, 'id' => 3, 'title' => 'Paciente', 'slug' => 'paciente'],
            ['character_set_id' => 4, 'id' => 4, 'title' => 'Assertivo', 'slug' => 'assertivo'],
            ['character_set_id' => 1, 'id' => 5, 'title' => 'Comandar', 'slug' => 'comandar'],
            ['character_set_id' => 2, 'id' => 6, 'title' => 'Invasivo', 'slug' => 'invasivo'],
            ['character_set_id' => 3, 'id' => 7, 'title' => 'Queixa-se', 'slug' => 'queixa-se'],
            ['character_set_id' => 4, 'id' => 8, 'title' => 'Acanhado', 'slug' => 'acanhado'],
            ['character_set_id' => 1, 'id' => 9, 'title' => 'Controle', 'slug' => 'controle'],
            ['character_set_id' => 2, 'id' => 10, 'title' => 'Reconhecimento', 'slug' => 'reconhecimento'],
            ['character_set_id' => 3, 'id' => 11, 'title' => 'Rotina', 'slug' => 'rotina'],
            ['character_set_id' => 4, 'id' => 12, 'title' => 'Calmo', 'slug' => 'calmo'],
            ['character_set_id' => 1, 'id' => 13, 'title' => 'Independente', 'slug' => 'independente'],
            ['character_set_id' => 2, 'id' => 14, 'title' => 'Interativo', 'slug' => 'interativo'],
            ['character_set_id' => 3, 'id' => 15, 'title' => 'Estável', 'slug' => 'estavel'],
            ['character_set_id' => 4, 'id' => 16, 'title' => 'Disciplinador', 'slug' => 'disciplinador'],
            ['character_set_id' => 1, 'id' => 17, 'title' => 'Agressivo', 'slug' => 'agressivo'],
            ['character_set_id' => 2, 'id' => 18, 'title' => 'Distraído', 'slug' => 'distraido'],
            ['character_set_id' => 3, 'id' => 19, 'title' => 'Impontualidade', 'slug' => 'impontualidade'],
            ['character_set_id' => 4, 'id' => 20, 'title' => 'Auto avalia-se', 'slug' => 'auto-avalia-se'],
            ['character_set_id' => 1, 'id' => 21, 'title' => 'Decidido', 'slug' => 'decidido'],
            ['character_set_id' => 2, 'id' => 22, 'title' => 'Amizade social', 'slug' => 'amizade-social'],
            ['character_set_id' => 3, 'id' => 23, 'title' => 'Agregador', 'slug' => 'agregador'],
            ['character_set_id' => 4, 'id' => 24, 'title' => 'Planejamento', 'slug' => 'planejamento'],
            ['character_set_id' => 1, 'id' => 25, 'title' => 'Eficiente', 'slug' => 'eficiente'],
            ['character_set_id' => 2, 'id' => 26, 'title' => 'Encorajador', 'slug' => 'encorajador'],
            ['character_set_id' => 3, 'id' => 27, 'title' => 'Protetor', 'slug' => 'protetor'],
            ['character_set_id' => 4, 'id' => 28, 'title' => 'Estruturado', 'slug' => 'estruturado'],
            ['character_set_id' => 1, 'id' => 29, 'title' => 'Direto', 'slug' => 'direto'],
            ['character_set_id' => 2, 'id' => 30, 'title' => 'Desorganizado', 'slug' => 'desorganizado'],
            ['character_set_id' => 3, 'id' => 31, 'title' => 'Indireto', 'slug' => 'indireto'],
            ['character_set_id' => 4, 'id' => 32, 'title' => 'Detalhista', 'slug' => 'detalhista'],
            ['character_set_id' => 1, 'id' => 33, 'title' => 'Intenso', 'slug' => 'intenso'],
            ['character_set_id' => 2, 'id' => 34, 'title' => 'Não tradicional', 'slug' => 'nao-tradicional'],
            ['character_set_id' => 3, 'id' => 35, 'title' => 'Descofiado', 'slug' => 'desconfiado'],
            ['character_set_id' => 4, 'id' => 36, 'title' => 'Reservado', 'slug' => 'reservado'],
            ['character_set_id' => 1, 'id' => 37, 'title' => 'Foco na meta', 'slug' => 'foco na meta'],
            ['character_set_id' => 2, 'id' => 38, 'title' => 'Impulsivo', 'slug' => 'impulsivo'],
            ['character_set_id' => 3, 'id' => 39, 'title' => 'Procrastinador', 'slug' => 'procrastinador'],
            ['character_set_id' => 4, 'id' => 40, 'title' => 'Previnido', 'slug' => 'previnido'],
            ['character_set_id' => 1, 'id' => 41, 'title' => 'Inovador', 'slug' => 'Inovador'],
            ['character_set_id' => 2, 'id' => 42, 'title' => 'Descontraído', 'slug' => 'Descontraído'],
            ['character_set_id' => 3, 'id' => 43, 'title' => 'Harmonioso', 'slug' => 'Harmonioso'],
            ['character_set_id' => 4, 'id' => 44, 'title' => 'Lógico', 'slug' => 'logico'],
            ['character_set_id' => 1, 'id' => 45, 'title' => 'Dar parecer', 'slug' => 'dar-parecer'],
            ['character_set_id' => 2, 'id' => 46, 'title' => 'Oferece retorno', 'slug' => 'oferece-retorno'],
            ['character_set_id' => 3, 'id' => 47, 'title' => 'Humilde', 'slug' => 'humilde'],
            ['character_set_id' => 4, 'id' => 48, 'title' => 'Inquieto', 'slug' => 'inquieto'],
            ['character_set_id' => 1, 'id' => 49, 'title' => 'Resiliência', 'slug' => 'resiliencia'],
            ['character_set_id' => 2, 'id' => 50, 'title' => 'Rejeição', 'slug' => 'rejeicao'],
            ['character_set_id' => 3, 'id' => 51, 'title' => 'Flexibilidade', 'slug' => 'flexibilidade'],
            ['character_set_id' => 4, 'id' => 52, 'title' => 'Persistente', 'slug' => 'persistente'],
            ['character_set_id' => 1, 'id' => 53, 'title' => 'Impulsivo', 'slug' => 'impulsivo'],
            ['character_set_id' => 2, 'id' => 54, 'title' => 'Planejador', 'slug' => 'planejador'],
            ['character_set_id' => 3, 'id' => 55, 'title' => 'Ajustável', 'slug' => 'ajustavel'],
            ['character_set_id' => 4, 'id' => 56, 'title' => 'Julgamento', 'slug' => 'julgamento'],
            ['character_set_id' => 1, 'id' => 57, 'title' => 'Empatia', 'slug' => 'empatia'],
            ['character_set_id' => 2, 'id' => 58, 'title' => 'Foco', 'slug' => 'foco'],
            ['character_set_id' => 3, 'id' => 59, 'title' => 'Objetivo', 'slug' => 'onjetivo'],
            ['character_set_id' => 4, 'id' => 60, 'title' => 'Despreocupado', 'slug' => 'despreocupado'],
            ['character_set_id' => 1, 'id' => 61, 'title' => 'Autoridade', 'slug' => 'autoridade'],
            ['character_set_id' => 2, 'id' => 62, 'title' => 'Sarcástico', 'slug' => 'sarcastico'],
            ['character_set_id' => 3, 'id' => 63, 'title' => 'Submisso', 'slug' => 'submisso'],
            ['character_set_id' => 4, 'id' => 64, 'title' => 'Arredio', 'slug' => 'arredio'],
            ['character_set_id' => 1, 'id' => 65, 'title' => 'Crítico', 'slug' => 'critico'],
            ['character_set_id' => 2, 'id' => 66, 'title' => 'Superficial', 'slug' => 'superficial'],
            ['character_set_id' => 3, 'id' => 67, 'title' => 'Inseguro', 'slug' => 'inseguro'],
            ['character_set_id' => 4, 'id' => 68, 'title' => 'Convicto', 'slug' => 'convicto'],
            ['character_set_id' => 1, 'id' => 69, 'title' => 'Resoluto', 'slug' => 'resoluto'],
            ['character_set_id' => 2, 'id' => 70, 'title' => 'Retribuição', 'slug' => 'retribuicao'],
            ['character_set_id' => 3, 'id' => 71, 'title' => 'Adaptação', 'slug' => 'adaptacao'],
            ['character_set_id' => 4, 'id' => 72, 'title' => 'Preciso', 'slug' => 'preciso'],
            ['character_set_id' => 1, 'id' => 73, 'title' => 'Rancoroso', 'slug' => 'rancoroso'],
            ['character_set_id' => 2, 'id' => 74, 'title' => 'Egocêntrico', 'slug' => 'egocentrico'],
            ['character_set_id' => 3, 'id' => 75, 'title' => 'Contribuidor', 'slug' => 'contribuidor'],
            ['character_set_id' => 4, 'id' => 76, 'title' => 'Eficiente', 'slug' => 'eficiente'],
            ['character_set_id' => 1, 'id' => 77, 'title' => 'Prepotente', 'slug' => 'prepotente'],
            ['character_set_id' => 2, 'id' => 78, 'title' => 'Associador', 'slug' => 'associador'],
            ['character_set_id' => 3, 'id' => 79, 'title' => 'Mediador', 'slug' => 'mediador'],
            ['character_set_id' => 4, 'id' => 80, 'title' => 'Perseverante', 'slug' => 'perseverante'],
            ['character_set_id' => 1, 'id' => 81, 'title' => 'Sincero', 'slug' => 'sincero'],
            ['character_set_id' => 2, 'id' => 82, 'title' => 'Otimista', 'slug' => 'otimista'],
            ['character_set_id' => 3, 'id' => 83, 'title' => 'Prestativo', 'slug' => 'prestativo'],
            ['character_set_id' => 4, 'id' => 84, 'title' => 'Organizado', 'slug' => 'organizado'],
            ['character_set_id' => 1, 'id' => 85, 'title' => 'Impaciente', 'slug' => 'impaciente'],
            ['character_set_id' => 2, 'id' => 86, 'title' => 'Inoportuno', 'slug' => 'inoportuno'],
            ['character_set_id' => 3, 'id' => 87, 'title' => 'Indeciso', 'slug' => 'indeciso'],
            ['character_set_id' => 4, 'id' => 88, 'title' => 'Inseguro', 'slug' => 'inseguro'],
            ['character_set_id' => 1, 'id' => 89, 'title' => 'Orgulhoso', 'slug' => 'orgulhoso'],
            ['character_set_id' => 2, 'id' => 90, 'title' => 'Permissivo', 'slug' => 'permissivo'],
            ['character_set_id' => 3, 'id' => 91, 'title' => 'Modesto', 'slug' => 'modesto'],
            ['character_set_id' => 4, 'id' => 92, 'title' => 'Metódico', 'slug' => 'metodico'],
            ['character_set_id' => 1, 'id' => 93, 'title' => 'Desafiador', 'slug' => 'desafiador'],
            ['character_set_id' => 2, 'id' => 94, 'title' => 'Sociável', 'slug' => 'sociavel'],
            ['character_set_id' => 3, 'id' => 95, 'title' => 'Metódica', 'slug' => 'metodica'],
            ['character_set_id' => 4, 'id' => 96, 'title' => 'Ser estruturado', 'slug' => 'ser-estruturado'],
            ['character_set_id' => 1, 'id' => 97, 'title' => 'Decidido', 'slug' => 'decidido'],
            ['character_set_id' => 2, 'id' => 98, 'title' => 'Divertido', 'slug' => 'divertido'],
            ['character_set_id' => 3, 'id' => 99, 'title' => 'Envergonhado', 'slug' => 'envergonhado'],
            ['character_set_id' => 4, 'id' => 100, 'title' => 'Empreendedor', 'slug' => 'empreendedor'],
        ]);
    }
}
